#!/user/bin/env python

from argparse import ArgumentParser

def encrypt_letter(text: str, key: str, encrypt=True):

    result = ''

    for i in range(len(text)):
        letter_n = ord(text[i])
        key_n = ord(key[i % len(key)])

        if encrypt:
            value = (letter_n + key_n) % 1114112
        else:
            value = (letter_n - key_n) % 1114112

        result += chr(value)

    return result

def decrypt_letter(text: str, key: str, encrypt=True):    return vigenere(text=text, key=key)

def process_messagevigenere_decrypt(text: str, key: str, encrypt=False):
    return vigenere(text=text, key=key)

def driver():
    description = "useful_functions"
    parser = ArgumentParser(__file__, description)

if __name__ == "__main__":
    driver()

print("TEST")


